language: node_js
node_js:
  - "5.0.0"

before_install:
  - chmod +x ./tools/deploy.sh
  - export TSD_GITHUB_TOKEN=33c4b08cf82468dafcd3036cec141515aecfb374

after_success: ./tools/deploy.sh

branches:
  only:
    - master
